# FindJPEG
set(JPEG_INCLUDE_DIR $ENV{REZ_LIBJPEG_ROOT}/include)
set(JPEG_LIBRARY $ENV{REZ_LIBJPEG_ROOT}/lib/libjpeg.so)

# FindOCIO
set(OCIO_PATH $ENV{REZ_OCIO_ROOT})
set(OpenColorIO_ROOT $ENV{REZ_OCIO_ROOT})

# FindOpenVDB
set(OpenVDB_ROOT $ENV{REZ_OPENVDB_ROOT})
